Importación de paquetes

In [ ]:
import pandas as pd
from ydata_profiling import ProfileReport

Leer el archivo

In [ ]:
path = "/content/VENTAS.csv"
ventas = pd.read_csv(path, encoding='latin-1',sep =',',header=0,)

In [ ]:
ventas.head()

In [ ]:
ventas.tail(1)

In [ ]:
ventas.columns

Index(['IdVendedor ', ' FechaVenta ', ' IdRegion ', ' IdEstado ', ' IdCiudad ',
       ' Producto ', ' IdFamilia ', ' IdGenero ', ' IdCategoria ',
       ' IdTipoProducto ', ' IdColor ', ' PrecioUnitario ',
       ' UnidadesVendidas ', ' PorcentajeRentabilidad ', ' IdTipoVenta'],
      dtype='object')

In [ ]:

print("Filas y columnas:", ventas.shape)

In [ ]:
print(ventas.dtypes)

In [ ]:
print(ventas.describe())

In [ ]:
print(ventas.isnull().sum())

In [ ]:
ventas.iloc[1, 5]

Cambio de nombre de columnas

In [ ]:
ventas = ventas.rename(columns={"IdRegion": "CdRegion"})

NameError: name 'ventas' is not defined

In [ ]:
ventas = ventas.rename(columns={
    "PrecioUnitario": "CostoUnitario",
    "UnidadesVendidas": "ArtVendidos"
})

In [ ]:
ventas.columns = ['CdVendedor','FechaVenta','CdRegion','CdEstado','CdCiudad','Producto','CdFamilia','CdGenero','CdCategoria','CdTipoProducto','CdColor','PrecioUnitario','UnCdadesVendCdas','PorcentajeRentabilCdad','CdTipoVenta',]

In [ ]:
ventas.columns

Eliminaciones

In [ ]:
ventas.drop("CdVendedor", axis=1, inplace=True)

In [ ]:
ventas["VentaTotal"] = ventas["UnCdadesVendCdas"] * ventas["PrecioUnitario"]

In [ ]:

ventas["Ventas_Doble"] = ventas["VentaTotal"]

Agrupaciones

In [ ]:
productos_mas_vendido = ventas.groupby("Producto")["UnCdadesVendCdas"].mean()
productos_mas_vendido.head()

Producto
Kid´s Street Footwear      162.458458
Men's Accesories            99.843284
Men's Apparel              409.259259
Men's Athletic Footwear    272.796435
Men's Street Footwear      522.086957
Name: UnCdadesVendCdas, dtype: float64

In [ ]:
productos_mas_vendido = ventas.groupby("Producto")["UnCdadesVendCdas"].sum()
productos_mas_vendido.head()

In [ ]:
print(ventas.groupby("Producto")["UnCdadesVendCdas"].agg(["sum","mean","max","min","count","size"]))

Profiling

In [ ]:
profile = ProfileReport(ventas, title="Reporte de Ventas", explorative=True)

In [ ]:
profile.to_notebook_iframe()

Manipulacion de n dataframes

In [ ]:
path_sales = "/content/VENTAS.csv"
venta_enero = pd.read_csv(path_sales, encoding='latin-1',sep =',',header=0,)

In [ ]:
path_sales = "/content/VENTAS.csv"
venta = pd.read_csv(path_sales, encoding='latin-1',sep =',',header=0,)

In [ ]:
path_sales = "/content/VENTAS.csv"
venta_febrero = pd.read_csv(path_sales, encoding='latin-1',sep =',',header=0,)

In [ ]:
path_vendor = "/content/VENDEDOR.csv"
vendedores = pd.read_csv(path_vendor, encoding='latin-1',sep =',',header=0,)

In [ ]:
path_product = "/content/TIPO DE PRODUCTO.csv"
productos = pd.read_csv(path_product, encoding='latin-1',sep =',',header=0,)

In [ ]:
path_product = "/content/REGIONES.csv"
region = pd.read_csv(path_product, encoding='latin-1',sep =',',header=0,)

In [ ]:
ventas.columns

Index(['IdVendedor ', ' FechaVenta ', ' IdRegion ', ' IdEstado ', ' IdCiudad ',
       ' Producto ', ' IdFamilia ', ' IdGenero ', ' IdCategoria ',
       ' IdTipoProducto ', ' IdColor ', ' PrecioUnitario ',
       ' UnidadesVendidas ', ' PorcentajeRentabilidad ', ' IdTipoVenta'],
      dtype='object')

In [ ]:
vendedores.columns

Index(['Vendedor', 'IdVendedor', 'Logo'], dtype='object')

In [ ]:
vendedores.head()

      Vendedor  IdVendedor                                               Logo
0       Amazon     1185732  https://rawcdn.githack.com/JopF32/Archivos-DA/...
1  Foot Locker     1128299  https://rawcdn.githack.com/JopF32/Archivos-DA/...
2       Kohl's     1189833  https://rawcdn.githack.com/JopF32/Archivos-DA/...
3       Adidas     1197831  https://rawcdn.githack.com/JopF32/Archivos-DA/...

In [ ]:
productos.columns

Index(['IdTipoProducto', 'TipoProducto'], dtype='object')

In [ ]:
productos.head()

   IdTipoProducto          TipoProducto
0               1       Gorra Ajustable
1               2  Camiseta Manga corta
2               3              Pantalon
3               4                   Mid
4               5       Plataforma baja

In [ ]:
venta_enero.shape

(9648, 15)

In [ ]:
venta_febrero.shape

(9648, 15)

In [ ]:
ventas_totales = pd.concat([venta_enero,venta_febrero], ignore_index=True)

In [ ]:
ventas_totales.shape

(19296, 15)

In [ ]:
ventas = ventas.rename(columns={" IdTipoProducto ": "IdTipoProducto","IdVendedor ": "IdVendedor"," IdRegion ": "IdRegion"})

In [ ]:
region.columns

Index(['IdRegion', 'Region'], dtype='object')

In [ ]:
Ventas_negocio = pd.merge(ventas, productos, on= "IdTipoProducto")

In [ ]:
Ventas_negocio = pd.merge(Ventas_negocio, vendedores, on= "IdVendedor", suffixes = ("_venta", "_vendor")).merge(region, on ="IdRegion")

In [ ]:
Ventas_negocio.head()

,IdVendedor,FechaVenta,IdRegion,IdEstado,IdCiudad,Producto,IdFamilia,IdGenero,IdCategoria,IdTipoProducto,IdColor,PrecioUnitario,UnidadesVendidas,PorcentajeRentabilidad,IdTipoVenta,TipoProducto,Vendedor,Logo,Region
0,1185732,17/08/2024,1,42,32,Men's Accesories,1,1,4,1,5,38,87,0.52,3,Gorra Ajustable,Amazon,https://rawcdn.githack.com/JopF32/Archivos-DA/...,Northeast
1,1185732,17/08/2024,1,42,32,Men's Accesories,1,1,4,1,5,36,72,0.51,3,Gorra Ajustable,Amazon,https://rawcdn.githack.com/JopF32/Archivos-DA/...,Northeast
2,1185732,17/08/2024,1,42,32,Men's Accesories,1,1,4,1,5,54,115,0.54,3,Gorra Ajustable,Amazon,https://rawcdn.githack.com/JopF32/Archivos-DA/...,Northeast
3,1185732,18/09/2024,1,42,32,Men's Accesories,1,1,4,1,5,24,68,0.54,3,Gorra Ajustable,Amazon,https://rawcdn.githack.com/JopF32/Archivos-DA/...,Northeast
4,1185732,18/09/2024,1,42,32,Men's Accesories,1,1,4,1,5,23,59,0.50,3,Gorra Ajustable,Amazon,https://rawcdn.githack.com/JopF32/Archivos-DA/...,Northeast

In [ ]:
Ventas_negocio.columns

Index(['IdVendedor', ' FechaVenta ', 'IdRegion', ' IdEstado ', ' IdCiudad ',
       ' Producto ', ' IdFamilia ', ' IdGenero ', ' IdCategoria ',
       'IdTipoProducto', ' IdColor ', ' PrecioUnitario ', ' UnidadesVendidas ',
       ' PorcentajeRentabilidad ', ' IdTipoVenta', 'TipoProducto', 'Vendedor',
       'Logo', 'Region'],
      dtype='object')

In [ ]:

Ventas_agregadas= Ventas_negocio.groupby([" Producto "," IdGenero ","IdRegion","TipoProducto"," IdCiudad "])[" UnidadesVendidas "].agg(["sum","count"])

In [ ]:
print(Ventas_agregadas)

                                                                              sum  \
 Producto                IdGenero  IdRegion TipoProducto          IdCiudad
Kid´s Street Footwear   3          1        Con detalles en azul 1           6239
                                                                 7           1261
                                                                 17           641
                                                                 21          1713
                                                                 32           394
...                                                                           ...
Women's Street Footwear 2          5        Puntera solida       23          6995
                                                                 31          3794
                                                                 32          5472
                                                                 33          7446
                                                                 35           486

                                                                             count
 Producto                IdGenero  IdRegion TipoProducto          IdCiudad
Kid´s Street Footwear   3          1        Con detalles en azul 1              22
                                                                 7              21
                                                                 17             11
                                                                 21             11
                                                                 32              5
...                                                                            ...
Women's Street Footwear 2          5        Puntera solida       23             26
                                                                 31             28
                                                                 32             14
                                                                 33             17
                                                                 35              9

[615 rows x 2 columns]